# Generated by Django 2.0 on 2018-12-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdecide',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserDecide',
        ),
    ]
